Trecco/ViewModels/Quadros/Forms/QuadroForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Trecco.ViewModels.Quadros.Forms
{
    public class QuadroForm
    {
        [DisplayName("Nome")]
        [Required(ErrorMessage = "O nome do quadro é obrigatório.")]
        [MaxLength(100, ErrorMessage ="O nome deve ser menor que 100 caracteres.")]
        public string Nome { get; set; }

        [DisplayName("Descrição")]
        [MaxLength(500, ErrorMessage = "A descrição deve ser menor que 500 caracteres.")]
        public string Descricao { get; set; }
    }
}

Trecco/ViewModels/Usuarios/CadastroForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Trecco.ViewModels.Usuarios
{
    public class CadastroForm
    {
        [DisplayName("Primeiro Nome")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [MaxLength(length: 50, ErrorMessage ="Este campo deve possuir, no máximo, 100 caracteres.")]
        public string Nome { get; set; }

        [DisplayName("Sobrenome")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [MaxLength(length: 200, ErrorMessage = "Este campo deve possuir, no máximo, 200 caracteres.")]
        public string Sobrenome { get; set; }

        [DisplayName("E-mail")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [EmailAddress(ErrorMessage = "Deve ser informado um e-mail válido.")]
        [MaxLength(length: 50, ErrorMessage = "Este campo deve possuir, no máximo, 50 caracteres.")]
        public string Email { get; set; }

        [DisplayName("Senha")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [MinLength(length:8, ErrorMessage = "A senha deve conter ao menos 8 caracteres.")]
        public string Senha { get; set; }

        [DisplayName("Confirmar Senha")]
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [Compare(otherProperty: "Senha", ErrorMessage = "A confirmação de senha deve ser igual a senha.")]
        public string ConfirmarSenha { get; set; }
    }
}

Trecco/Controllers/GruposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trecco.Dominio.Entidades;
using Trecco.Dominio.Servicos;

namespace Trecco.Controllers
{
    public class GruposController : Controller
    {
        private readonly IGruposService service;

        public GruposController()
        {
            service = new GruposService();
        }

        public ActionResult List(int idQuadro)
        {
            var grupos = service.ObterAtivos(new QuadroID(idQuadro));

            ViewBag.Quadro = service.ObterQuadro(new QuadroID(idQuadro));

            return View(grupos);
        }

        public ActionResult Create(int idQuadro)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(int idQuadro, FormCollection formulario)
        {
            var nomeGrupo = formulario["txtNomeGrupo"];

            service.Incluir(nomeGrupo, new QuadroID(idQuadro));

            return RedirectToAction("List");
        }

        public ActionResult Edit(int idQuadro, int id)
        {
            var grupo = service.Obter(new GrupoID(id));

            return View(grupo);
        }

        [HttpPost]
        public ActionResult Edit(int idQuadro, int id, FormCollection formulario)
        {
            var nomeGrupo = formulario["txtNomeGrupo"];

            service.Alterar(new GrupoID(id), nomeGrupo);

            return RedirectToAction("List");
        }

        public ActionResult MoveLeft(int idQuadro, int id)
        {
            service.MoverParaAEsquerda(new QuadroID(idQuadro), new GrupoID(id));
            return RedirectToAction("List");
        }

        public ActionResult MoveRight(int idQuadro, int id)
        {
            service.MoverParaADireita(new QuadroID(idQuadro), new GrupoID(id));

            return RedirectToAction("List");
        }

        public ActionResult Delete(int idQuadro, int id)
        {
            service.Remover(new GrupoID(id));

            return RedirectToAction("List", new { idQuadro });
        }

    }
}

Trecco/Controllers/LixeiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trecco.Dominio.Entidades;
using Trecco.Dominio.Servicos;

namespace Trecco.Controllers
{
    public class LixeiraController : Controller
    {
        private readonly IQuadrosService _service;

        public LixeiraController()
        {
            _service = new QuadrosService();
        }

        public ActionResult List()
        {
            var quadros = _service.ObterQuadrosInativos();

            return View(quadros);
        }

        public ActionResult Delete(int id)
        {
            _service.ExcluirPermanentemente(new QuadroID(id));

            TempData["Mensagem"] = "Quadro removido.";

            return RedirectToAction("list");
        }

        public ActionResult Restore(int id)
        {
            _service.ReativarQuadro(new QuadroID(id));

            TempData["Mensagem"] = "Quadro restaurado.";

            return RedirectToAction("list", "quadros");
        }
    }
}

Trecco/Controllers/QuadrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trecco.Dominio.Entidades;
using Trecco.Dominio.Servicos;
using Trecco.ViewModels.Quadros.Forms;

namespace Trecco.Controllers
{
    public class QuadrosController : Controller
    {
        private readonly IQuadrosService service;

        public QuadrosController()
        {
            this.service = new QuadrosService();
        }

        public ActionResult List()
        {
            var quadros = service.ObterQuadros();

            return View(quadros);
        }  

        public ActionResult Delete(int id)
        {
            service.InativarQuadro(new QuadroID(id));

            return RedirectToAction("list");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(QuadroForm formulario)
        {
            if (ModelState.IsValid)
            {
                service.CriarQuadro(formulario.Nome);

                TempData["MensagemSucesso"] = "Quadro criado!";

                return RedirectToAction("List");
            }
            else
            {
                return View(formulario);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var quadro = service.ObterQuadro(new QuadroID(id));

            if (quadro != null)
                return View(
                    new QuadroForm
                    {
                        Nome = quadro.Nome
                    });
            else
                return HttpNotFound("Quadro não encontrado");
        }

        [HttpPost]
        public ActionResult Edit(int id, QuadroForm formulario)
        {
            service.AtualizarQuadro(new QuadroID(id), formulario.Nome);

            TempData["MensagemSucesso"] = "Quadro atualizado!";

            return RedirectToAction("List");
        }
    }
}

Trecco/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trecco.Dominio.Fabricas;
using Trecco.Dominio.Servicos;
using Trecco.ViewModels.Usuarios;

namespace Trecco.Controllers
{
    public class UsuariosController : Controller
    {
        private IUsuariosService _service;

        public UsuariosController()
        {
            _service = UsuariosServiceFactory.CriarUsuariosService();
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CadastroForm formulario)
        {
            if (!ModelState.IsValid) return View(formulario);

            if (_service.ExisteUsuario(formulario.Email))
            {
                ModelState.AddModelError("Email", "Já existe um usuário com este e-mail");
                return View(formulario);
            }

            _service.CriarUsuario(formulario.Email, formulario.Nome, formulario.Sobrenome, formulario.Senha);

            return RedirectToAction("List", "Quadros");
        }
    }
}

Trecco/Views/Grupos/Create.cshtml
@{
    ViewBag.Title = "Criar novo Grupo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar novo grupo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quadro</h4>
        <hr />
        <div class="form-group">
            <label for="txtNomeGrupo">Nome</label>
            <input type="text" class="form-control" id="txtNomeGrupo" name="txtNomeGrupo" placeholder="Insira o nome do novo grupo">
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "List")
</div>

Trecco/Views/Grupos/Edit.cshtml
@model Trecco.Dominio.Entidades.Grupo

@{
    ViewBag.Title = $"Alterar grupo - {Model.Nome}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quadro</h4>
        <hr />
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label for="txtNomeQuadro">Nome</label>
            <input type="text" class="form-control" id="txtNomeGrupo" name="txtNomeGrupo" placeholder="Insira o nome do grupo" value="@Model.Nome">
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "List")
</div>

Trecco/Views/Grupos/List.cshtml
@model IEnumerable<Trecco.Dominio.Entidades.Grupo>

@{
    ViewBag.Title = "Grupos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Quadro.Nome</h2>

<p>
    @Html.ActionLink("Criar grupo", "Create") | @Html.ActionLink("Voltar", "List", "Quadros")
</p>
<div class="row flex-nowrap">
@foreach (var item in Model)
{
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header">@Html.DisplayFor(modelItem => item.Nome)</div>
            <div class="card-body">
                @Html.DisplayFor(modelItem => item.Posicao)
                |
                @Html.ActionLink("<<", "MoveLeft", new { idQuadro = item.Quadro.Id.Valor, id = item.Id.Valor })
                |
                @Html.ActionLink(">>", "MoveRight", new { idQuadro = item.Quadro.Id.Valor, id = item.Id.Valor })
                @*@foreach (var id in Enumerable.Range(1, 5))
        {*@
                <!-- TODO: Aqui entrarão os cartões! -->
                @*<div class="card">
            <div class="card-body">
                <h5 class="card-title">Card title that wraps to a new line</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
        </div>*@
                @*}*@
            </div>
        </div>
    </div>
}
</div>

Trecco/Views/Lixeira/List.cshtml
@model IEnumerable<Trecco.Dominio.Entidades.Quadro>


@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quadros Removidos</h2>

<p>
    @Html.ActionLink("Voltar para Meus Quadros", "List", "Quadros")
</p>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.DataDeCriacao)</th>
        <th>@Html.DisplayNameFor(model => model.DataDeAlteracao)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Nome)</td>
        <td>@Html.DisplayFor(modelItem => item.DataDeCriacao)</td>
        <td>@Html.DisplayFor(modelItem => item.DataDeAlteracao)</td>
        <td>
            @Html.ActionLink("Restaurar", "Restore", new { id = item.Id.Valor }) |
            @Html.ActionLink("Remover Permanentemente", "Delete", new { id = item.Id.Valor })
        </td>
    </tr>
    }

</table>

Trecco/Views/Quadros/Create.cshtml
@model Trecco.ViewModels.Quadros.Forms.QuadroForm

@{
    ViewBag.Title = "Criar novo quadro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar Novo Quadro</h2>

@{ Html.RenderPartial("_Form", Model); }

<div>
    @Html.ActionLink("Voltar", "List")
</div>

Trecco/Views/Quadros/Edit.cshtml
@model Trecco.ViewModels.Quadros.Forms.QuadroForm

@{
    ViewBag.Title = $"Alterar quadro - {Model.Nome}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar quadro - @Model.Nome</h2>

@{ Html.RenderPartial("_Form", Model); }

<div>
    @Html.ActionLink("Voltar", "List")
</div>

Trecco/Views/Quadros/List.cshtml
@model IEnumerable<Trecco.Dominio.Entidades.Quadro>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quadros</h2>

<p>
    @Html.ActionLink("Criar quadro", "Create") | @Html.ActionLink("Ver Lixeira", "List", "Lixeira")
</p>
@if (TempData.ContainsKey("MensagemSucesso"))
{
    <p>
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    </p>
}

<div class="row">
    @foreach (var item in Model)
    {
        Html.RenderPartial("_CardQuadro", item);
    }
</div>

Trecco/Views/Quadros/_CardQuadro.cshtml
@model Trecco.Dominio.Entidades.Quadro

<div class="col-md-3">
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <h2 class="card-title">
                @Html.RouteLink(Model.Nome, "Grupos", new { idQuadro = Model.Id.Valor }, new { @class = "text-lg" })
            </h2>
            <!-- TODO: Trocar para a descrição do quadro -->
            @*<div>*@

            @*Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus est non tincidunt lacinia. Mauris molestie lorem quam, quis commodo justo aliquam ac.*@
            @*</div>*@
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Alterado em: @Html.DisplayFor(modelItem => Model.DataDeAlteracao)</small>
                <div role="group">
                    @{
                        var buttonId = $"btnAcoes-{Model.Id.Valor}";

                        <button id="@buttonId" type="button" class="btn btn-link btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            ...
                        </button>
                        <div class="dropdown-menu" aria-labelledby="@buttonId">
                            @Html.ActionLink("Editar", "Edit", new { id = Model.Id.Valor }, new { @class = "dropdown-item", role = "button" })
                            @Html.ActionLink("Excluir", "Delete", new { id = Model.Id.Valor }, new { @class = "dropdown-item", role = "button" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Trecco/Views/Quadros/_Form.cshtml
@model Trecco.ViewModels.Quadros.Forms.QuadroForm

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", placeholder = "Insira o nome do quadro aqui." })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao)
            @Html.ValidationMessageFor(model => model.Nome)
            @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", placeholder = "Insira a descrição para este quadro aqui." })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Trecco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
    
    @RenderSection("scripts", required: false)
</body>
</html>

Trecco/Views/Usuarios/Create.cshtml
@model Trecco.ViewModels.Usuarios.CadastroForm

@{
    ViewBag.Title = "Novo Usuário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crie sua nova conta</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger small" }, "div")
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            <small id="emailHelp" class="form-text text-muted">Digite o seu primeiro nome.</small>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome)
            @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger small" }, "div")
            @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
            <small id="emailHelp" class="form-text text-muted">Digite o seu sobrenome.</small>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger small" }, "div")
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            <small id="emailHelp" class="form-text text-muted">Seu e-mail será utilizado para o acesso ao aplicativo.</small>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label" })
            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger small" }, "div")
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control" })
            <small id="senhaHelp" class="form-text text-muted">A senha deverá conter no mínimo 8 caracteres.</small>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "control-label" })
            @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger small" }, "div")
            @Html.PasswordFor(model => model.ConfirmarSenha, new { @class = "form-control" })
            <small id="confirmarSenhaHelp" class="form-text text-muted">A confirmação da senha deve ser idêntica a senha escolhida.</small>
        </div>

        <input type="submit" value="Criar uma nova conta" class="btn btn-success" />
    </div>
}